stages:
  - containers
  - prebuild

# Check that all commits are signed-off for the DCO.
# Skip on "virt-viewer" namespace, since we only need to run
# this test on developer's personal forks from which
# merge requests are submitted
check-dco:
  stage: prebuild
  image: registry.gitlab.com/libvirt/libvirt-ci/check-dco:master
  script:
    - /check-dco virt-viewer
  except:
    variables:
      - $CI_PROJECT_NAMESPACE == 'virt-viewer'

ctr-check-dco:
  <<: *container_job_definition
  variables:
    NAME: check-dco
