stages:
  - prebuild

# Check that all commits are signed-off for the DCO. Skip
# on master branch and -maint branches, since we only need
# to test developer's personal branches.
dco:
  stage: prebuild
  # XXX change to a virt-viewer specific image later
  image: quay.io/libvirt/buildenv-libvirt-fedora-31:latest
  script:
    - ./scripts/require-dco.py
  only:
    - branches
  except:
    - /^v.*-maint$/
    - master
