#!/bin/sh

if test -z "$1"
then
    echo "syntax: $0 PATH-TO-LCITOOL"
    exit 1
fi

LCITOOL=$1

if ! test -x "$LCITOOL"
then
    echo "$LCITOOL is not executable"
    exit 1
fi

HOSTS=$($LCITOOL hosts | grep -v freebsd | sed -e 's/libvirt-//')

for host in $HOSTS
do
    if test "$host" = "fedora-rawhide"
    then
        for cross in mingw32 mingw64
        do
            $LCITOOL dockerfile libvirt-$host libvirt,libvirt-glib,gtk-vnc,virt-viewer --cross $cross >$host-cross-$cross.Dockerfile
        done
    fi

    if test "$host" = "centos-8" || test "$host" = "centos-stream"
    then
        $LCITOOL dockerfile libvirt-$host libvirt+minimal,libvirt-glib,gtk-vnc,virt-viewer > $host.Dockerfile
    else
        $LCITOOL dockerfile libvirt-$host libvirt+dist,libvirt-glib+dist,gtk-vnc+dist,virt-viewer > $host.Dockerfile
    fi
done
